config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :subventions, only: [:index] do
    resources :subvention_requests, only: [:new, :create, :show, :index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subvention.rb
class Subvention < ApplicationRecord
  has_many :subvention_requests

  def date_ok?
    Date.today >= start_date && Date.today <= end_date
  end
end

app/models/subvention_request.rb
class SubventionRequest < ApplicationRecord
  belongs_to :subvention

  validates :email, format: { with: /\A[^\s\/,:!]+@[^\s,:!\/]+\.[a-zA-Z]{2}[a-zA-Z]?\z/, message: "L'adresse email doit être valide." }
  validates :amount_asked, inclusion: { in: 1..100_000, message: "Le montant du remboursement ne doit pas\
   dépasser celui autorisé par la subvention" }
  validates :justif_path, presence: true

  mount_uploader :justif_path, JustifUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/subvention_requests_controller.rb
class SubventionRequestsController < ApplicationController
  def new
    @subvention = Subvention.find(params[:subvention_id])
    @subvention_request = SubventionRequest.new
  end

  def create
    @subvention = Subvention.find(params[:subvention_id])
    @subvention_request = SubventionRequest.new(subvention_request_params)
    @subvention_request.subvention = @subvention
    if subvention_request_params[:amount_asked].to_i * 100 <= @subvention.amount \
      && @subvention_request.save(subvention_request_params)\
      && date_condition(@subvention.start_date, @subvention.end_date)
      redirect_to subvention_subvention_request_path(@subvention, @subvention_request)
    else
      @subvention_request.errors.add(:amount_asked, message: "Le montant du remboursement ne doit pas\
   dépasser celui autorisé par la subvention") if subvention_request_params[:amount_asked].to_i * 100 > @subvention.amount
      @subvention_request.errors.add(:date, message: "Vous ne pouvez pas encore/plus bénéficier de cette subvention.")\
       if !date_condition(@subvention.start_date, @subvention.end_date)
      render :new
    end
  end

  def show
    @subvention = Subvention.find(params[:subvention_id])
    @subvention_request = SubventionRequest.find(params[:id])
  end

  def index
  end

  private

  def subvention_request_params
    params.require(:subvention_request).permit(:email, :justif_path, :amount_asked)
  end

  def date_condition(start_date, end_date)
    Date.today >= start_date && Date.today <= end_date
  end
end

app/controllers/subventions_controller.rb
class SubventionsController < ApplicationController
  def index
    @subventions = Subvention.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Clan</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
    <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://www.magazette.fr/wp-content/uploads/google-plex-office.jpg');">
  <div class="banner-content">
    <h1>Le Clan</h1>
    <p style="display: inline-block;"><span id="typed"></span></p>
    <br>
    <a class="btn btn-primary btn-lg" href=<%= subventions_path %>>Découvrez toutes les subventions dont vous pouvez profiter!</a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "clan.jpg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



      <!-- Links when logged in -->
      <%= link_to "Subventions", subventions_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/subvention_requests/new.html.erb
<h1>Demande de remboursement pour <strong><%= @subvention.name %></strong></h1>
<br>
<br>

<%= simple_form_for [@subvention, @subvention_request] do |f| %>
  <% if @subvention_request.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @subvention_request.errors.messages.each do |message| %>
            <li><%= message[1][0] %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="form-group">
    <div class="row">
      <div class="col-xs-2 col-xs-offset-3">
        <%= f.label :email, "Votre email" %>
      </div>
      <div class="col-xs-4">
        <%= f.text_field :email, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-xs-5">
        <%= f.label :amount_asked, "Montant du remboursement (max. autorisé: #{@subvention.amount / 100}€)" %>
      </div>
      <div class="col-xs-4">
        <%= f.text_field :amount_asked, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-xs-5">
        <%= f.label :justif_path, "Joindre un justificatif" %>
      </div>
      <div class="col-xs-2">
        <%= f.input :justif_path, class: 'form-control', label: false %>
        <%= f.input :justif_path_cache, as: :hidden %>
      </div>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col-xs-2 col-xs-offset-4">
      <%= f.submit class: 'btn btn-primary', value:"Envoyer la demande de remboursement" %>
    </div>
  </div>
<% end %>

app/views/subvention_requests/show.html.erb
<h1>Votre demande a été envoyée et sera bientôt traitée.</h1>
<br>
<br>
<div style="display: flex; justify-content: center; align-items: center;">
  <div><%= link_to "Retour à l'accueil", subventions_path, class:"btn btn-primary" %></div>
  <div><%= cl_image_tag @subvention_request.justif_path, height: 300, width: 400, crop: :fill %></div>
</div>

app/views/subventions/index.html.erb
<h1>Voici la liste des subventions proposées:</h1><br>

<div class="row">

  <% @subventions.each do |subvention| %>
  <div class="col-xs-6 col-sm-4">
    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.1)), url(<%= subvention.photo %>);">
      <div class="card-category">A hauteur de <%= subvention.amount / 100 %>€</div>
      <div class="card-description">
        <h4><%= subvention.name %></h4>
        <p>Du <%= subvention.start_date.strftime("%d/%m/%Y") %> au <%= subvention.end_date.strftime("%d/%m/%Y") %></p>
      </div>
      <div class="card-user"><h5><%= subvention.subvention_requests.size %></h5>
        <p>participants</p>
      </div>
      <% if subvention.date_ok? %>
        <a class="card-link" href=<%= new_subvention_subvention_request_path(subvention) %>></a>
      <% else %>
        <div class="card-time-out"><h1>EXPIRE</h1></div>
      <% end %>
    </div>
  </div>
  <% end %>

</div>